[[constraint]]
  name = "github.com/Sirupsen/logrus"
  branch = "master"

[[constraint]]
  name = "github.com/bitrise-io/go-utils"
  revision = "3cd2fc1c516caded20f67b53428cb793a82ad454"

[[constraint]]
  name = "github.com/bitrise-io/goinp"
  branch = "master"

[[constraint]]
  name = "github.com/stretchr/testify"
  branch = "master"

[[constraint]]
  name = "github.com/urfave/cli"
  branch = "master"

[[constraint]]
  name = "gopkg.in/yaml.v2"
  branch = "v2"
